#!/usr/bin/env bash
# Build the app with the configured public BASE_PATH and rsync the dist/
# contents up to DEPLOY_HOST:DEPLOY_DIR/BASE_PATH/ — preserving structure
# and deleting anything no longer in the build.
#
# Reads BASE_PATH, DEPLOY_HOST, DEPLOY_DIR from the environment (or .env
# in the project root). Run from the project root:  scripts/deploy.sh
set -euo pipefail

# Move to the project root so relative paths resolve regardless of where
# this was invoked from.
cd "$(dirname "$0")/.."

# Load .env if present. We parse it line-by-line (rather than `source`)
# so that variables already set in the environment WIN over .env defaults
# — that lets an inline override like `BASE_PATH=/foo/ scripts/deploy.sh`
# do what the user expects, instead of being silently clobbered by a
# `BASE_PATH=...` line in .env.
if [ -f .env ]; then
  while IFS= read -r line || [ -n "$line" ]; do
    # Skip blank lines and comments.
    [[ "$line" =~ ^[[:space:]]*(#|$) ]] && continue
    # Match KEY=VALUE (KEY is a valid shell identifier); skip anything malformed.
    if [[ "$line" =~ ^[[:space:]]*([A-Za-z_][A-Za-z_0-9]*)=(.*)$ ]]; then
      key="${BASH_REMATCH[1]}"
      val="${BASH_REMATCH[2]}"
      # Strip a single layer of surrounding single OR double quotes.
      if [[ "$val" == \"*\" ]]; then val="${val#\"}"; val="${val%\"}"; fi
      if [[ "$val" == \'*\' ]]; then val="${val#\'}"; val="${val%\'}"; fi
      # Only set if the variable isn't already in the environment.
      # `${!key+x}` is bash's "is set" probe (returns 'x' if set, even
      # to empty; empty otherwise).
      if [[ -z "${!key+x}" ]]; then
        export "$key=$val"
      fi
    fi
  done < .env
fi

: "${BASE_PATH:?BASE_PATH must be set (e.g. /cubedex/)}"
: "${DEPLOY_HOST:?DEPLOY_HOST must be set (e.g. example.com)}"
: "${DEPLOY_DIR:?DEPLOY_DIR must be set (e.g. example.com)}"

# Normalise BASE_PATH to /<...>/ — exactly one leading and one trailing
# slash, regardless of how many the input had. A bare/empty path collapses
# to a single "/".
while [[ "$BASE_PATH" == /* ]]; do BASE_PATH="${BASE_PATH#/}"; done
while [[ "$BASE_PATH" == */ ]]; do BASE_PATH="${BASE_PATH%/}"; done
if [[ -z "$BASE_PATH" ]]; then BASE_PATH="/"; else BASE_PATH="/${BASE_PATH}/"; fi
# Strip ALL trailing slashes on DEPLOY_DIR so concatenation with BASE_PATH
# (which always starts with /) never produces a doubled separator.
while [[ "$DEPLOY_DIR" == */ ]]; do DEPLOY_DIR="${DEPLOY_DIR%/}"; done

target="${DEPLOY_HOST}:${DEPLOY_DIR}${BASE_PATH}"

echo "→ Building with BASE_PATH=${BASE_PATH}"
BASE_PATH="${BASE_PATH}" npm run build

# Drop a small .htaccess into the build output so the deployed directory
# survives shift-reload (which bypasses the service worker) and any path
# under it falls back to index.html — the app is a single-page PWA with
# no real on-disk routes. Both directives require the server to permit
# them via `AllowOverride` (FileInfo + Indexes), which is the default on
# most shared hosting; if your server is locked down, set that in the
# vhost or move these into the vhost itself.
echo "→ Writing dist/.htaccess (BASE_PATH=${BASE_PATH})"
cat > dist/.htaccess <<EOF
# Auto-generated by scripts/deploy.sh — do not hand-edit; re-runs of the
# deploy script will overwrite this file.

# Apache normally needs to be told that index.html is the default file
# for a directory request (e.g. https://example.com${BASE_PATH}). Without
# this, shift-reload at the app's root returns 404.
DirectoryIndex index.html

# Single-page-app fallback: any URL inside the app that doesn't resolve
# to an on-disk file gets served index.html (which then boots the SPA).
# Path is relative to the document root, NOT the filesystem.
FallbackResource ${BASE_PATH}index.html
EOF

echo "→ Syncing dist/ → ${target}"
# `dist/` (trailing slash) tells rsync to copy the CONTENTS of dist into
# the target directory rather than copying the dist folder itself.
rsync -av --delete dist/ "${target}"

echo "✓ Deployed to ${target}"
